version: "3.9"
services:
  frontend:
    image: nginx:latest
    container_name: static-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    image: node:18
    container_name: api-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["node", "server.js"]
    ports:
      - "5000:5000"
