# docker/Dockerfile.secure (SEGURO)
# 1. Imagen Base Segura: Alpine es más pequeño y con menos paquetes
FROM node:18-alpine 

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --omit=dev
COPY . .

# 2. Usuario No Root (Mejor Práctica)
# Crea un usuario de bajo privilegio (UID 1001)
RUN addgroup -g 1001 appgroup && adduser -u 1001 -G appgroup -S appuser
RUN chown -R appuser:appgroup /usr/src/app

# Ejecuta el resto de comandos y la aplicación como el usuario no root
USER appuser

EXPOSE 3000
CMD [ "node", "src/server.js" ]